resources:
# - deployment/cp4ba-catalogsource-ci.yaml
- deployment/cp4ba-subscription-ci.yaml

### BAW DEPLOYMENT ###
#- deployment/cp4ba-baw-catalogsource.yaml
#- deployment/cp4ba-baw-subscription.yaml